// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPKURkhfT-JiGq2mGxlJn5d5-MPifd264',
    appId: '1:692921337221:web:a4756cc22fc068337330ec',
    messagingSenderId: '692921337221',
    projectId: 'aasha-becd0',
    authDomain: 'aasha-becd0.firebaseapp.com',
    storageBucket: 'aasha-becd0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxirC2WV3Uw-q79G9B_uf5gdA4xr5W_OU',
    appId: '1:692921337221:android:b40dcfb0d228c9b07330ec',
    messagingSenderId: '692921337221',
    projectId: 'aasha-becd0',
    storageBucket: 'aasha-becd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN14g5l2IHaVfDEfAjlpdQgnfVp87e3Pk',
    appId: '1:692921337221:ios:4b45aa408f8ca1f57330ec',
    messagingSenderId: '692921337221',
    projectId: 'aasha-becd0',
    storageBucket: 'aasha-becd0.firebasestorage.app',
    iosBundleId: 'com.example.aasha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN14g5l2IHaVfDEfAjlpdQgnfVp87e3Pk',
    appId: '1:692921337221:ios:4b45aa408f8ca1f57330ec',
    messagingSenderId: '692921337221',
    projectId: 'aasha-becd0',
    storageBucket: 'aasha-becd0.firebasestorage.app',
    iosBundleId: 'com.example.aasha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPKURkhfT-JiGq2mGxlJn5d5-MPifd264',
    appId: '1:692921337221:web:96c47bc23138684f7330ec',
    messagingSenderId: '692921337221',
    projectId: 'aasha-becd0',
    authDomain: 'aasha-becd0.firebaseapp.com',
    storageBucket: 'aasha-becd0.firebasestorage.app',
  );
}
